### ISSUE TITLE
Valence calculation for conjunction.

### ISSUE THREAD

**Issue by rtw30606** [trinker/sentimentr#24]
hi

As part of preparation for teaching sentimentr, I prepared examples showing the calculation process. However, I can't reconcile the difference between my interpretation and the sentiment computed value.

> sample = c("You're crazy, but I love you.")
> sentiment(sample, n.before = 2, n.after=2, amplifier.weight=.8, but.weight=.9)
   element_id sentence_id word_count sentiment
1:          1           1          6 0.6205374
> (-1*(1 -.9) + 1*(1.9))/sqrt(6)
[1] 0.7348469

Thanks

Rick

**Comment by trinker** [comment]
I think this may be an artifact of me trying to explain the process in symbol notation rather than as an algorithm as pseudo-code.  Anyway here's how it gets calculated.



There are two chunks with n=2 before and after sentiment words.  The comma stops a window around the sentiment word so we have:

```
chunk1 = "you're crazy"
chunk2 = "but I love you"
```

Now we calculate `A` for each which is amplification.  chunk one has no amplifiers so it is not amplified.  The `but` contractions are treated as amplifiers and so `A` for chunk2 is:
```
A = ((1 - w_neg) * a)*amp.weight
A = 1*1.9*.8
A = 1.52
```
Where:    
`w_neg = neg %% 2`    
`a = 1 + but.weight`     

So now we can calculate the chunk prime which I give as:  `c′i, j = ∑((1 + wamp + wdeamp)⋅wi, j, kp(−1)2 + wneg)`

so:

```
chunk1' = 1 * -1 * (-1)^2 = -1
chunk2' = 2.52 * 1 * (-1)^2 = 2.52
```

now we can do `(chunk1' + chunk2')/(n^.5)`:

```
(-1 + 2.52)/sqrt(6) = .6205374
```

**Comment by rtw30606** [comment]
Thanks Tyler for the explanation.

**Comment by trinker** [comment]
I'm going to close this for now.  If you wish to explore this further feel free to re-open.

**Comment by rtw30606** [comment]
Thanks Tyler

I appreciate your promptness.

Cheers ~ Rick
