### ISSUE TITLE
Error in UseMethod("sentiment_by") :    no applicable method for 'sentiment_by' applied to an object of class "data.frame"

### ISSUE THREAD

**Issue by KKulma** [trinker/sentimentr#70]
I'm following the example from the README file and trying to apply `get_sentences()` and `sentiment_by()` to a data.frame:

```

> str(mini_clean)
'data.frame':	46123 obs. of  3 variables:
 $ convo_id  : chr  "M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01" "M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01" "M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01" "M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01" ...
 $ speaker   : chr  "agent" "visitor" "visitor" "agent" ...
 $ clean_text: chr  "     good afternoon how can i help you  " "     hi there   i m looking to make a claim  i left my laptop on a train and they train company have been unable to find it " "     the online claim process says to check whether it is worthwhile claiming " "     okay let me look at your policy for you sorry to hear this has happened though " ...

```

But when I execute the code:

```
test_sentiment = mini_clean %>% 
  mutate(sentence_split = get_sentences(clean_text)) %>% 
  sentiment_by(sentence_split, list(convo_id, speaker))
```

I get the following error:

> Error in UseMethod("sentiment_by") : 
>   no applicable method for 'sentiment_by' applied to an object of class "data.frame"

Why is that?

**Comment by trinker** [comment]
Because the first argument of sentiment_by is a vector not `data`.

I know what is wrong and why but would ask you use `?sentiment_by` to view
the help documentation and look at the examples at the bottom and see if
you can figure it out from the documentation first.  Please let me know if
that helps.

On Dec 20, 2017 10:03 AM, "Kasia" <notifications@github.com> wrote:

I'm following the example from the README file and trying to apply
get_sentences() and sentiment_by() to a data.frame:


> str(mini_clean)
'data.frame':	46123 obs. of  3 variables:
 $ convo_id  : chr  "M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01"
"M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01"
"M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01"
"M3ZWM3NzgzYWI2YTRkYWM4_2017-11-01" ...
 $ speaker   : chr  "agent" "visitor" "visitor" "agent" ...
 $ clean_text: chr  "     good afternoon how can i help you  " "
hi there   i m looking to make a claim  i left my laptop on a train
and they train company have been unable to find it " "     the online
claim process says to check whether it is worthwhile claiming " "
okay let me look at your policy for you sorry to hear this has
happened though " ...


But when I execute the code:

test_sentiment = mini_clean %>%
  mutate(sentence_split = get_sentences(clean_text)) %>%
  sentiment_by(sentence_split, list(convo_id, speaker))

I get the following error:

Error in UseMethod("sentiment_by") :
no applicable method for 'sentiment_by' applied to an object of class
"data.frame"

Why is that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/trinker/sentimentr/issues/70>, or mute the thread

**Comment by KKulma** [comment]
@trinker: `sentence_split` in my example is not `data`, but the text variable. My code is essentially an exact copy of the example in README file:

```
presidential_debates_2012 %>%
    dplyr::mutate(dialogue_split = get_sentences(dialogue)) %$%
    sentiment_by(dialogue_split, list(person, time)) 
```

**Comment by trinker** [comment]
`%$%` vs. `%>%`

**Comment by KKulma** [comment]
That's it! What does `%$%` do ?? googling it doesn't give me much

**Comment by KKulma** [comment]
Great, I overlooked that, thanks! You learn something [new](https://www.rdocumentation.org/packages/magrittr/versions/1.5/topics/%25%24%25) every day!

**Comment by snvv** [comment]
with the readme example

> presidential_debates_2012 %>%
>   get_sentences() %$%
>   sentiment_by(dialogue, list(person, time))

I get "Error in get_sentences.data.frame(.) : object 'text.var' not found"

> class(presidential_debates_2012)
> [1] "tbl_df"     "tbl"        "data.frame"

Same outcome both with %>% and %$%
